[package]
name = "panics"
version = "0.1.0"
edition = "2021"

[dependencies]
helpers = { workspace = true }
tracing-subscriber = { workspace = true, default-features = true, features = ["fmt"] }
tracing-panic = { workspace = true }
