[package]
name = "what_to_log"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
log = { version = "0.4", features = ["std"] }

[dev-dependencies]
helpers = { path = "../../../helpers" }
