[package]
name = "prom_recorder"
version = "0.1.0"
edition = "2021"

[dependencies]
metrics = { workspace = true }
metrics-exporter-prometheus = { workspace = true }
metrics-util = { workspace = true }
ureq = { workspace = true }
rustls = { workspace = true }