[package]
name = "log_filter_koan"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "min_level"
path = "src/bins/min_level.rs"

[[bin]]
name = "module"
path = "src/bins/module.rs"

[dependencies]
assert_cmd = { workspace = true }
log = { workspace = true, features = ["std"] }
